- hosts: webservers
  user: foobar # FIXME: Use Docker API
  sudo: true
  vars_files:
    - vars.yml

  tasks:
    - name: Install MySQL
      action: apt pkg=$item state=installed
      with_items:
        - python-mysqldb
        - mysql-server
        - mysql-client

    - name: Start the MySQL service
      action: service name=mysql state=started


    - name: Create deploy user for mysql
      mysql_user: user="deploy" host="%" password={{mysql_root_password}} priv=*.*:ALL,GRANT


    - name: Copy .my.cnf file with root password credentials
      template: src=templates/.my.cnf dest=/etc/mysql/my.cnf owner=root mode=0600

    - name: Update mysql root password for all root accounts
      mysql_user: name=root host={{item}} password={{mysql_root_password}}
      with_items:
        - 127.0.0.1
        - ::1
        - localhost
